Add link to main README with installation instruction
rescript-lang/create-rescript-app pull request #41
Opened 2024-01-07 01:28 UTC by aspeddro

For now, since we don't have a flag `--example nextjs`

ReScript website landing page will link the URL to the `README.md` of each template. 

https://github.com/rescript-association/rescript-lang.org/pull/760

2024-01-07 13:01 UTC, fhammerschmidt requested changes

2024-01-07 13:01 UTC, fhammerschmidt commented on templates/rescript-template-nextjs/README.md
> +- [Instalattion](../../README.md)
Installation

2024-01-07 13:01 UTC, fhammerschmidt commented on templates/rescript-template-vite/README.md
> +- [Instalattion](../../README.md)
Installation

2024-01-07 17:57 UTC, fhammerschmidt approved these changes

2024-01-08 12:47 UTC, aspeddro commented on templates/rescript-template-nextjs/README.md
> +- [Instalattion](../../README.md)
https://github.com/rescript-lang/create-rescript-app/pull/41/commits/a222ac228e24e1782ef3630db817e4bf7ec73ca3

2024-01-08 14:04 UTC, merged